---
version: '3'
services:
  app:
    image: mosheh/eem-frontend:latest
    ports:
     - "8080:80"
  proxy:
    build: proxy
    ports:
     - "80:80"
  
  eem-pg-api:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:postgres@10.0.0.10:5432/eem
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: terndb
    restart: unless-stopped